### ISSUE TITLE
Annual Review Meeting Feb 2024

### ISSUE THREAD

**Issue by kstrohmayer** [semify-eda/tristan#15]
Collection of topics for the annual review meeting

**Dates:**
- Sync: 2. Feb
- Presentation to EU: 5. - 6. Feb

**Tasks**
- [ ] WP1: ?
- [x] WP2 (@adam-hrvth ): Update project report slides (3 pages)
- [x] <s> WP2: Short presentation for industry partners 
  - Length to be defined, target < 10min </s>
- [x] <s> WP6: Video Demonstration </s> 

CC: @kstrohmayer @adam-hrvth @mole99

**Comment by adam-hrvth** [comment]
The individual presentation for industry partners is no longer required.

I have updated the [report slides](https://nxp1.sharepoint.com/:p:/r/sites/KDT-RISCV/_layouts/15/Doc.aspx?sourcedoc=%7BA5D2CD11-E271-4AE3-9295-14C7F29C0E58%7D&file=TRISTAN_WP2%20Review%20Meeting_BRU_20231220.pptx&action=edit&mobileredirect=true) (pp 117-119).  We could do a short review, next time when we are all in the office. 

I contacted Rob regarding the video demonstration. I would suggest doing a performance improvement comparison, with and without the custom instructions. Afterward, we can share it either on our Google Drive or on GitHub and link it to the presentation.

**Comment by adam-hrvth** [comment]
Regarding the demo video, Rob mentioned that there's no feedback from the EU officials regarding the available time for presentation, so it's unlikely that we have to take any action. There's an option to upload it to SharePoint or do a short live presentation during the review, but in our case, since there isn't much to show, I'll inform him that we don't plan to present it—unless there's an objection

**Comment by mole99** [comment]
@adam-hrvth I can't access the report via SharePoint. Could you send it to me by e-mail?

**Comment by adam-hrvth** [comment]
@mole99 I added the slides to our [Google Drive](https://docs.google.com/presentation/d/13jsf4BbnQGLx_U9EbsA39XS9Y8uZz1ky/edit?usp=sharing&ouid=116851939288601517356&rtpof=true&sd=true).

**Comment by mole99** [comment]
Looks good to me. Nice block diagram!
